services:
  java:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: