name: Java CI with JDK 23

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'adoptopenjdk'  # Ou 'corretto', 'zulu', etc., dependendo da distribuição que você escolher
          java-version: '23'


      - name: Build with Maven
        run: mvn clean install -DskipTests=false


      - name: Run tests
        run: mvn test


